refactor: change webkms to fit refactored kms service, add bdd tests
hyperledger/aries-framework-go pull request #3079
Opened 2021-12-01 14:52 UTC by vkubiv

Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>

**Title:**
Change format of remote kms api calls to correspond to changes in kms service api

**Description:**
Make changes to webkms and remote crytro to work with new version of kms service.
Add bdd tests for webkms and remote crypto.

2021-12-01 16:00 UTC, aholovko requested changes

2021-12-02 15:23 UTC, aholovko commented on pkg/crypto/webkms/remotecrypto.go
> +		return nil, fmt.Errorf("posting Sing returned http error: %s", resp.Status)
"Sing" -> "Sign" :)

2021-12-02 15:47 UTC, aholovko approved these changes

2021-12-03 09:27 UTC, fqutishat approved these changes

2021-12-03 09:36 UTC, merged